
export interface NDDashboardTableView {
    Area: string,
    Eq: number,
    // Sold   : number,
    Dhl: number,
    Ar: number,
    Sbl: number,
    Pmt: number,
    Pmm: number,
    Ticket: number,
    Mtc: number,
    Ws: number,
    Mast: number,
    Oris: number,
    Elite: number,
    Ck: number,
    Yes: number,
    Time: number,
}

export interface NDDashboardByArea {
    Eq: number, 
    Dhl: number,
    Ar: number,
    Sbl: number,
    Pmt: number,
    Pmm: number,
    Ticket: number,
    Mtc: number,
    Ws: number,
    Mast: number,
    Oris: number,
    Elite: number,
    Ck: number,
    Yes: number,
    Time: number,
}
